from __future__ import annotations
import csv,json,os
from datetime import date,datetime,timedelta
from typing import Any
OUT='docs/index.html'
def load_json(p:str,d:Any):
    try:
        if os.path.exists(p): return json.load(open(p,encoding='utf-8'))
    except Exception: pass
    return d
def read_csv(p:str):
    try:
        if os.path.exists(p): return list(csv.DictReader(open(p,encoding='utf-8')))
    except Exception: pass
    return []
def target(): return os.environ.get('TARGET') or os.environ.get('WNBA_TARGET_DATE') or str(date.today())
def yday(t):
    try: return str(datetime.strptime(t,'%Y-%m-%d').date()-timedelta(days=1))
    except Exception: return str(date.today()-timedelta(days=1))
def first(paths):
    for p in paths:
        r=read_csv(p)
        if r: return r
    return []
def games_from_markets(markets):
    out={}
    for m in markets or []:
        g=m.get('game') or ''
        if g and g not in out: out[g]={'game':g,'status':'Pregame','source':'sportsbook consensus','total':'','spread':''}
    return list(out.values())
def payload():
    t=target(); y=yday(t)
    master=load_json('data/dashboard/wnba_master.json',{})
    sb=load_json('data/dashboard/wnba_sportsbook_consensus.json',{})
    preds=load_json(f'predictions/predictions_{t}.json',{})
    master_games=master.get('games',[]) if isinstance(master,dict) else []
    today=[g for g in master_games if g.get('bucket')=='today'] or first([f'data/raw/scores_{t}.csv','data/raw/scores_today.csv']) or preds.get('games',[]) or games_from_markets(sb.get('markets',[]))
    yesterday=[g for g in master_games if g.get('bucket')=='yesterday'] or first([f'data/raw/scores_{y}.csv'])
    master_props=master.get('props',[]) if isinstance(master,dict) else []
    return {'target_date':master.get('target_date') or t,'generated_at_utc':master.get('generated_at_utc') or datetime.utcnow().isoformat()+'Z','master':master,'terminal':load_json('data/dashboard/terminal_ui.json',{}),'predictions':preds,'today_scores':today,'yesterday_scores':yesterday,'player_points':first([f'data/raw/player_points_{t}.csv','data/raw/player_points_today.csv']) or master_props,'line_shopping':first([f'data/raw/line_shopping_best_{t}.csv',f'data/raw/line_shopping_{t}.csv','data/raw/line_shopping_best_today.csv','data/raw/line_shopping_today.csv']),'sportsbook_consensus':sb,'odds_health':load_json('data/dashboard/wnba_odds_health.json',{}),'stats_quality':load_json('data/dashboard/wnba_stats_quality.json',{}),'source_health':load_json('data/dashboard/wnba_source_health.json',{}),'autonomous_agent':load_json('data/dashboard/wnba_autonomous_agent.json',{}),'decision':load_json('data/dashboard/wnba_decision_engine_final.json',{}),'consensus':load_json('data/dashboard/wnba_consensus_engine.json',{}),'matchups':load_json('data/dashboard/wnba_matchup_intelligence.json',{}),'portfolio':load_json('data/dashboard/wnba_portfolio_dashboard.json',{}),'risk':load_json('data/dashboard/wnba_risk_allocation.json',{}),'grading':load_json('data/dashboard/wnba_results_grading.json',{}),'ai_coach':load_json('data/dashboard/wnba_ai_coach.json',{}),'monte_carlo':load_json('data/dashboard/wnba_monte_carlo_engine.json',{}),'projection_ai':load_json('data/dashboard/wnba_projection_ai.json',{}),'market':load_json('data/dashboard/wnba_market_engine.json',{}),'learning':load_json('data/dashboard/wnba_self_learning.json',{})}
HTML='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WNBA Model</title><style>:root{--p:#0d1424;--m:#8b96ad;--t:#edf2ff;--l:#22304c;--g:#00e5a0;--r:#ff6b7a;--b:#7aa2ff;--y:#ffd166}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top right,#112441,#070912 45%,#05060b);color:var(--t);font-family:Courier New,monospace}.app{max-width:1220px;margin:auto;padding:16px 10px 60px}.top{display:flex;justify-content:space-between;gap:12px}.ey{font-size:12px;letter-spacing:.3em;color:#86a8ff}.title{font-size:30px;font-weight:900;letter-spacing:.08em}.sub,.small{color:var(--m);font-size:12px}.pill{border:1px solid var(--l);background:#10192b;border-radius:999px;padding:8px 12px;height:max-content}.tabs{display:flex;gap:8px;overflow:auto;padding:10px;background:var(--p);border:1px solid var(--l);border-radius:18px;position:sticky;top:0;z-index:5;margin-top:14px}.tab{white-space:nowrap;background:transparent;color:#94a3b8;border:0;padding:10px 12px;border-radius:12px;font-weight:900;font-family:inherit}.tab.a{background:#1c2b49;color:white}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card,.panel{background:linear-gradient(180deg,#101827,#0a0f1d);border:1px solid var(--l);border-radius:18px;padding:15px;margin-top:12px}.label{font-size:11px;color:#7f8ba2;text-transform:uppercase;letter-spacing:.18em}.val{font-size:27px;font-weight:900;color:var(--g);margin-top:6px}.red{color:var(--r)}.blue{color:var(--b)}.gold{color:var(--y)}.pt{font-size:18px;font-weight:900;margin-bottom:10px}.row{border:1px solid #1d2a43;background:#0b1220;border-radius:14px;padding:12px;margin:8px 0}.rt{display:flex;justify-content:space-between;gap:10px}.score{font-size:22px;font-weight:900}.tag{font-size:11px;border:1px solid #2c3c5f;border-radius:999px;padding:4px 8px;color:#b9c8e8}input{width:100%;background:#0a1020;border:1px solid var(--l);border-radius:12px;color:white;padding:12px;font-family:inherit;margin-top:12px}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #1f2b45;padding:10px 8px;text-align:left;font-size:12px}th{color:#89a2cc;text-transform:uppercase}.empty{text-align:center;color:#7f8ba2;padding:28px}@media(max-width:860px){.grid,.grid2,.grid3{grid-template-columns:1fr}.title{font-size:24px}table{display:block;overflow:auto}}</style><script>const DATA=__DATA__;</script></head><body><div class="app"><div class="top"><div><div class="ey">WNBA MODEL</div><div class="title">Daily Report</div><div class="sub" id="sub"></div></div><div class="pill" id="pill"></div></div><div class="tabs" id="tabs"></div><div id="content"></div></div><script>
const tabs=[['games','Games'],['matchups','Matchups'],['props','Player Props'],['books','Sportsbooks'],['best','Best Bets'],['ai','AI Center'],['live','Live'],['results','Results'],['portfolio','Portfolio'],['health','Data Health']];
const $=i=>document.getElementById(i), A=x=>Array.isArray(x)?x:[], S=(v,d='-')=>v===undefined||v===null||v===''?d:v, P=(o,ks,d)=>{for(const k of ks){if(!o||o[k]===undefined)return d;o=o[k]}return o};
function fmtDate(v){let d=new Date(v);return isNaN(d)?new Date().toLocaleString():d.toLocaleString()}
function game(g){return S(g.game)||[S(g.away_team||P(g,['away','name'],''),''),S(g.home_team||P(g,['home','name'],''),'')].filter(Boolean).join(' @ ')||'WNBA Game'}
function score(g){let a=S(g.away_score||P(g,['away','score'],''),'');let h=S(g.home_score||P(g,['home','score'],''),'');return a!==''||h!==''?a+'-'+h:S(g.score,'')}
function cards(){let sb=P(DATA,['sportsbook_consensus','summary'],{}),oh=P(DATA,['odds_health','summary'],{}),ms=P(DATA,['master','summary'],{}),sq=P(DATA,['stats_quality','summary'],{}),lp=ms.players||sq.live_players||sq.player_rows||0;return `<div class="grid"><div class="card"><div class="label">Odds</div><div class="val ${sb.markets?'':'red'}">${sb.markets?'Loaded':'Missing'}</div><div class="small">${S(sb.markets,0)} markets</div></div><div class="card"><div class="label">Props</div><div class="val">Loaded</div><div class="small">${S(ms.props||oh.active_prop_rows||DATA.player_points?.length||sb.markets,0)} rows</div></div><div class="card"><div class="label">Stats</div><div class="val ${lp?'':'red'}">${lp?'Loaded':'Missing'}</div><div class="small">${lp} players</div></div><div class="card"><div class="label">Books</div><div class="val">${A(sb.books_detected).length}</div><div class="small">${A(sb.books_detected).join(', ')}</div></div></div>`}
function games(){let g=A(DATA.today_scores);let y=A(DATA.yesterday_scores);return cards()+`<div class="grid2"><div class="panel"><div class="pt">Today's Games</div>${g.map(x=>`<div class="row"><div class="rt"><div><b>${game(x)}</b><div class="small">${S(x.start_time||x.tip||x.commence_time||x.date,'Time TBD')} · ${S(x.status||x.game_status||x.source,'Pregame')}</div></div><div class="score">${score(x)}</div></div><div style="margin-top:10px"><span class="tag">Spread ${S(x.spread||x.spread_home)}</span> <span class="tag">Total ${S(x.total)}</span></div></div>`).join('')||'<div class="empty">No games loaded.</div>'}</div><div class="panel"><div class="pt">Yesterday Results</div>${y.map(x=>`<div class="row"><div class="rt"><div><b>${game(x)}</b><div class="small">Final</div></div><div class="score">${score(x)}</div></div></div>`).join('')||'<div class="empty">No previous results loaded.</div>'}</div></div>`}
function matchups(){let m=A(P(DATA,['matchups','matchups'],[]));if(!m.length)m=A(DATA.today_scores);return `<div class="grid2">${m.slice(0,40).map(x=>`<div class="card"><div class="label">Matchup</div><div class="pt">${game(x)}</div><span class="tag">Pace ${S(x.pace||x.pace_score)}</span> <span class="tag">Edge ${S(x.edge||x.matchup_score)}</span> <span class="tag">Lean ${S(x.lean||x.signal)}</span><p class="small">${S(x.note||x.summary||x.reason,'Team analysis will grow as data collects.')}</p></div>`).join('')||'<div class="empty">No matchup cards yet.</div>'}</div>`}
function propData(){return A(DATA.player_points).length?A(DATA.player_points):A(P(DATA,['master','props'],[])).length?A(P(DATA,['master','props'],[])):A(P(DATA,['sportsbook_consensus','markets'],[]))}
function props(){return `<input id="q" placeholder="Search player, team, stat" oninput="filterProps()"><div class="panel"><div class="pt">Player Props</div><table><thead><tr><th>Player</th><th>Stat</th><th>Line</th><th>Proj</th><th>Side</th><th>Book</th></tr></thead><tbody id="pb">${propRows(propData())}</tbody></table></div>`}
function propRows(p){return p.slice(0,160).map(r=>`<tr><td>${S(r.player)}</td><td>${S(r.stat)}</td><td>${S(r.line||r.consensus_line)}</td><td>${S(r.pred||r.ai_projection||r.projection)}</td><td>${S(r.signal||r.side)}</td><td>${S(r.book||r.best_book||r.best_over_book||r.source)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No props loaded.</td></tr>'}
function filterProps(){let q=$('q').value.toLowerCase();$('pb').innerHTML=propRows(propData().filter(r=>JSON.stringify(r).toLowerCase().includes(q)))}
function books(){let sb=DATA.sportsbook_consensus||{},m=A(sb.markets);return cards()+`<div class="panel"><div class="pt">Best Available Lines</div><table><thead><tr><th>Player</th><th>Stat</th><th>Line</th><th>Best Over</th><th>Best Under</th><th>Books</th></tr></thead><tbody>${m.slice(0,130).map(x=>`<tr><td>${S(x.player)}</td><td>${S(x.stat)}</td><td>${S(x.consensus_line)}</td><td>${S(x.best_over_book)} ${S(x.best_over_price)}</td><td>${S(x.best_under_book)} ${S(x.best_under_price)}</td><td>${A(x.books).join(', ')}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No sportsbook markets.</td></tr>'}</tbody></table></div>`}
function best(){let b=A(P(DATA,['decision','top_decisions'],[]));if(!b.length)b=A(P(DATA,['consensus','top_consensus'],[]));return `<div class="grid2">${b.slice(0,30).map(r=>`<div class="card"><div class="label">${S(r.final_action||r.recommendation||r.action,'Watch')}</div><div class="pt">${S(r.player)} ${S(r.stat)} ${S(r.signal)}</div><div class="small">${S(r.game)} · ${S(r.book||r.best_book)}</div><span class="tag">Score ${S(r.final_score||r.consensus_score||r.confidence)}</span> <span class="tag">Line ${S(r.line)}</span></div>`).join('')||'<div class="empty">No best bets yet.</div>'}</div>`}
function ai(){let c=A(P(DATA,['ai_coach','coach_cards'],[]));return `<div class="grid3"><div class="card"><div class="label">Agent</div><div class="val">${S(P(DATA,['autonomous_agent','agent_action'],'-'))}</div></div><div class="card"><div class="label">Monte Carlo</div><div class="val">${S(P(DATA,['monte_carlo','summary','rows'],0))}</div></div><div class="card"><div class="label">Projection AI</div><div class="val">${S(P(DATA,['projection_ai','summary','rows'],0))}</div></div></div><div class="panel"><div class="pt">AI Coach</div>${c.slice(0,10).map(x=>`<div class="row"><b>${S(x.play)}</b><div class="small">${S(x.coach_note)}</div></div>`).join('')||'<div class="empty">No coach notes yet.</div>'}</div>`}
function live(){let l=A(DATA.today_scores).filter(x=>String(S(x.status||x.game_status,'')).toLowerCase().includes('live'));return `<div class="panel"><div class="pt">Live Center</div>${l.map(x=>`<div class="row"><div class="rt"><b>${game(x)}</b><div class="score">${score(x)}</div></div></div>`).join('')||'<div class="empty">No games live right now.</div>'}</div>`}
function results(){let g=DATA.grading||{};return `<div class="grid"><div class="card"><div class="label">Completed</div><div class="val">${S(g.graded_this_run,0)}</div></div><div class="card"><div class="label">Wins</div><div class="val">${S(g.wins,0)}</div></div><div class="card"><div class="label">Losses</div><div class="val red">${S(g.losses,0)}</div></div><div class="card"><div class="label">Win Rate</div><div class="val gold">${S(g.win_rate,'-')}</div></div></div><div class="panel"><div class="pt">Lessons</div><pre>${JSON.stringify(g.lessons||['No completed results found yet.'],null,2)}</pre></div>`}
function portfolio(){let p=DATA.portfolio||{},r=DATA.risk||{},card=A(p.recommended_card||r.allocation);return `<div class="grid"><div class="card"><div class="label">Card Size</div><div class="val">${card.length}</div></div><div class="card"><div class="label">Exposure</div><div class="val">${S(P(r,['summary','total_exposure'],0))}</div></div><div class="card"><div class="label">Exposure %</div><div class="val">${S(P(r,['summary','exposure_pct'],0))}</div></div><div class="card"><div class="label">Teams</div><div class="val">${S(P(r,['summary','teams'],0))}</div></div></div><div class="panel"><div class="pt">Allocation</div>${card.slice(0,20).map(x=>`<div class="row"><b>${S(x.player)} ${S(x.stat)} ${S(x.signal)}</b><div class="small">${S(x.game)} · stake ${S(x.capped_amount||x.capped_stake||x.recommended_stake)}</div></div>`).join('')||'<div class="empty">No allocation built yet.</div>'}</div>`}
function health(){let matrix=A(P(DATA,['master','source_matrix'],[]));let old=Object.entries(P(DATA,['source_health','sources'],{}));return cards()+`<div class="panel"><div class="pt">Data Source Matrix</div>${matrix.length?matrix.map(v=>`<div class="row"><div class="rt"><b>${S(v.source)}</b><span class="tag">${S(v.status)}</span></div><div class="small">${S(v.detail)} · rows ${S(v.rows,0)}</div></div>`).join(''):old.map(([k,v])=>`<div class="row"><div class="rt"><b>${S(v.label,k)}</b><span class="tag">${S(v.status)}</span></div><div class="small">${k}</div></div>`).join('')||'<div class="empty">No source health built.</div>'}</div>`}
function render(t='games'){$('tabs').innerHTML=tabs.map(x=>`<button class="tab ${x[0]===t?'a':''}" onclick="render('${x[0]}')">${x[1]}</button>`).join('');$('sub').textContent=`Slate ${S(DATA.target_date,'-')} · Updated ${fmtDate(DATA.generated_at_utc)}`;$('pill').textContent=`${S(P(DATA,['sportsbook_consensus','summary','markets'],0),0)} odds markets`;$('content').innerHTML={games,matchups,props,books,best,ai,live,results,portfolio,health}[t]();scrollTo(0,0)}render();
</script></body></html>'''
def main():
    os.makedirs('docs',exist_ok=True)
    html=HTML.replace('__DATA__',json.dumps(payload(),separators=(',',':'),ensure_ascii=False))
    open(OUT,'w',encoding='utf-8').write(html)
    print('Dashboard navigation v2 written from master database')
if __name__=='__main__': main()
