from __future__ import annotations
from pathlib import Path
HTML=Path('docs/index.html')
CSS=r'''<style id="v4-prop-bet-cards-style">
.betCardGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:14px 0}.betCard{border:1px solid #263854;background:linear-gradient(180deg,#101a2d,#08101c);border-radius:18px;padding:16px}.betCardTop{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.betGrade{font-size:30px;font-weight:900;color:#00e39b}.betMeta{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.betMetrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.betMetric{border:1px solid #1e2a43;border-radius:12px;padding:10px;background:#07101d}.betMetric b{display:block;font-size:17px;margin-top:4px}.betTrend{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin-top:10px}.betTrend .betMetric b{font-size:15px}.betList{margin:10px 0 0;padding-left:18px;color:#b8c8e8}.betRisk{color:#ffd166}.betNotice{border:1px solid #304365;border-radius:14px;padding:12px;color:#b8c8e8;background:#0a1322}.betSectionTitle{display:flex;justify-content:space-between;gap:12px;align-items:center}.whyGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.gradeA{color:#00e39b}.gradeB{color:#80a8ff}.gradeC{color:#ffd166}.gradePass{color:#ff4d67}@media(max-width:900px){.betCardGrid{grid-template-columns:1fr}.betMetrics,.betTrend,.whyGrid{grid-template-columns:1fr 1fr}}
</style>'''
SCRIPT=r'''<script id="v4-prop-bet-cards-script">
(function(){
 const arr=v=>Array.isArray(v)?v:[];const esc=v=>typeof E==='function'?E(v):String(v??'');const val=(v,d='—')=>v===undefined||v===null||v===''?d:v;
 const pct=v=>v===undefined||v===null?'—':`${(Number(v)*100).toFixed(1)}%`;const money=v=>v===undefined||v===null?'—':`${Number(v)>=0?'+':''}${(Number(v)*100).toFixed(1)}%`;
 function cards(){return arr(DATA.master?.best_bets).filter(x=>x&&String(x.source||'').includes('calibrated_prop_bet_card_v2'))}
 function trend(c,key){const t=c?.trend?.[key]||{};return t.sample?`${t.hits}/${t.sample} (${Math.round(Number(t.hit_rate||0)*100)}%)`:'—'}
 function gclass(g){return String(g).startsWith('A')?'gradeA':String(g).startsWith('B')?'gradeB':String(g).startsWith('C')?'gradeC':'gradePass'}
 function card(c){const reasons=arr(c.reasons).map(x=>`<li>✓ ${esc(x)}</li>`).join('');const risks=arr(c.risks).map(x=>`<li>⚠ ${esc(x)}</li>`).join('');return `<div class="betCard"><div class="betCardTop"><div><div class="label mono">${esc(val(c.action,'WATCH'))}</div><h3 class="mono">${esc(c.player)} ${esc(c.stat)} ${esc(c.side)}</h3><div class="small mono">${esc(c.game)} · ${esc(val(c.sportsbook))} ${esc(val(c.odds))}</div></div><div class="betGrade mono ${gclass(c.letter_grade)}">${esc(val(c.letter_grade))}</div></div><div class="betMeta"><span class="chip mono">Line ${esc(val(c.line))}</span><span class="chip mono">Proj ${esc(val(c.projection))}</span><span class="chip mono">Edge ${esc(val(c.projection_edge))}</span><span class="chip mono">Grade ${esc(val(c.research_grade))}</span><span class="chip mono">Consensus ${esc(val(c.consensus_score))}</span></div><div class="betMetrics"><div class="betMetric"><div class="label mono">AI Win %</div><b class="mono">${pct(c.simulation_probability)}</b></div><div class="betMetric"><div class="label mono">Expected Value</div><b class="mono">${money(c.expected_value)}</b></div><div class="betMetric"><div class="label mono">Fair Odds</div><b class="mono">${esc(val(c.fair_odds))}</b></div><div class="betMetric"><div class="label mono">Kelly Stake</div><b class="mono">${esc(val(c.recommended_units))}u</b></div></div><div class="betTrend"><div class="betMetric"><div class="label mono">L5</div><b class="mono">${trend(c,'last5')}</b></div><div class="betMetric"><div class="label mono">L10</div><b class="mono">${trend(c,'last10')}</b></div><div class="betMetric"><div class="label mono">L20</div><b class="mono">${trend(c,'last20')}</b></div><div class="betMetric"><div class="label mono">Season</div><b class="mono">${trend(c,'season')}</b></div><div class="betMetric"><div class="label mono">Vs Opp</div><b class="mono">${trend(c,'opponent')}</b></div><div class="betMetric"><div class="label mono">${esc(val(c.location,'Split'))}</div><b class="mono">${trend(c,'location')}</b></div></div><div class="betMeta"><span class="chip mono">Line move ${esc(val(c.line_movement))}</span><span class="chip mono">CLV ${esc(val(c.clv_projection))}</span><span class="chip mono">${esc(val(c.book_count,0))} books</span></div><div class="whyGrid">${reasons?`<div><div class="label mono">Why</div><ul class="betList">${reasons}</ul></div>`:''}${risks?`<div><div class="label mono">Risk Factors</div><ul class="betList betRisk">${risks}</ul></div>`:''}</div></div>`}
 const originalProps=window.props||props;window.props=function(){const ranked=cards();const summary=`<div class="section"><div class="betSectionTitle"><div><h2 class="mono">Player Props & Best Bets V2</h2><div class="small mono">Ranked by expected value after simulation, history, quality, and sportsbook-consensus gates. Grade is not win probability.</div></div><span class="chip mono">${ranked.length} ranked</span></div>${ranked.length?`<div class="betCardGrid">${ranked.map(card).join('')}</div>`:'<div class="betNotice mono">No props currently meet BET or LEAN thresholds. The model is allowed to pass.</div>'}</div>`;return summary+originalProps()};window.best=window.props;
})();
</script>'''
def replace_block(html,start,end,replacement):
 i=html.find(start)
 if i<0:return html
 j=html.find(end,i)
 if j<0:return html
 return html[:i]+replacement.strip()+html[j+len(end):]
def main():
 if not HTML.exists():raise SystemExit('docs/index.html missing')
 html=HTML.read_text(encoding='utf-8');html=replace_block(html,'<style id="v4-prop-bet-cards-style">','</style>',CSS) if 'id="v4-prop-bet-cards-style"' in html else html.replace('</head>',CSS+'</head>');html=replace_block(html,'<script id="v4-prop-bet-cards-script">','</script>',SCRIPT) if 'id="v4-prop-bet-cards-script"' in html else html.replace('</body>',SCRIPT+'</body>');HTML.write_text(html,encoding='utf-8');print('Dashboard prop bet cards V2 active')
if __name__=='__main__':main()
