from __future__ import annotations

import argparse
import json
import os
import re
import unicodedata
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

SPORT = "basketball_wnba"
BASE = "https://api.the-odds-api.com/v4"
ET = ZoneInfo("America/New_York")
DASH = Path("data/dashboard")
RAW = Path("data/raw")
MARKETS = [
    "player_points", "player_rebounds", "player_assists", "player_threes",
    "player_points_rebounds_assists", "player_points_rebounds",
    "player_points_assists", "player_rebounds_assists",
]
PRODUCTION_BOOKS = {
    "draftkings": "DraftKings",
    "fanduel": "FanDuel",
    "fanatics": "Fanatics",
}
PRODUCTION_BOOKMAKERS = ",".join(sorted(PRODUCTION_BOOKS))
STAT_MAP = {
    "player_points": "PTS", "player_rebounds": "REB", "player_assists": "AST",
    "player_threes": "3PM", "player_points_rebounds_assists": "PRA",
    "player_points_rebounds": "PR", "player_points_assists": "PA",
    "player_rebounds_assists": "RA",
}


def normalize_book_key(book: dict) -> str:
    """Return the exact supported Odds API bookmaker key, or an empty string."""
    key = re.sub(r"[^a-z0-9]+", "", str(book.get("key") or "").casefold())
    return key if key in PRODUCTION_BOOKS else ""


def filter_supported_bookmakers(payload: dict) -> tuple[dict, set[str], set[str]]:
    """Quarantine unsupported books before any canonical price is calculated."""
    clean = dict(payload)
    kept = []
    observed: set[str] = set()
    rejected: set[str] = set()
    for raw_book in payload.get("bookmakers", []) or []:
        if not isinstance(raw_book, dict):
            continue
        raw_label = str(raw_book.get("key") or raw_book.get("title") or "unknown").strip()
        key = normalize_book_key(raw_book)
        if not key:
            rejected.add(raw_label)
            continue
        book = dict(raw_book)
        book["key"] = key
        book["title"] = PRODUCTION_BOOKS[key]
        kept.append(book)
        observed.add(key)
    clean["bookmakers"] = kept
    return clean, observed, rejected


def load_json(path: Path, default):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def event_date(value: str) -> str:
    dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    return dt.astimezone(ET).date().isoformat()


def player_key(value: str) -> str:
    """Normalize sportsbook/player-source naming without guessing identity."""
    text = unicodedata.normalize("NFKD", str(value or ""))
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.casefold().replace("’", "'")
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return " ".join(text.split())


def roster_map() -> dict[str, str]:
    out: dict[str, str] = {}
    master = load_json(DASH / "wnba_master.json", {})
    for row in master.get("players", []) if isinstance(master, dict) else []:
        name = str(row.get("player") or row.get("name") or "").strip()
        team = str(row.get("team") or "").strip()
        if name and team:
            out[player_key(name)] = team
    live = load_json(RAW / "wnba_players_live.json", {})
    if isinstance(live, dict):
        for key, row in live.items():
            if not isinstance(row, dict):
                continue
            name = str(row.get("player") or key or "").strip()
            team = str(row.get("team") or "").strip()
            if name and team:
                out[player_key(name)] = team
    return out


def resolve_team(player: str, away: str, home: str, teams_by_player: dict[str, str]) -> tuple[str, str]:
    """Resolve only from owned roster data and require membership in this event."""
    team = str(teams_by_player.get(player_key(player)) or "").strip()
    if team in {away, home}:
        return team, "roster"
    return "", "unresolved"


def sync_canonical_manifest(target: str, props_output: dict) -> None:
    """Keep the deploy gate aligned with the authoritative current slate.

    The morning rollover already refreshes wnba_master.json immediately before
    player-prop ingestion. Historically the manifest was only regenerated by a
    separate canonical workflow, allowing a green rollover to leave yesterday's
    manifest behind and block Pages. Regenerate the minimal canonical contract
    here from same-run authoritative files; the dedicated canonical builder may
    later overwrite it with its richer step audit.
    """
    master = load_json(DASH / "wnba_master.json", {})
    master_target = str(master.get("target_date") or "")[:10]
    if master_target != target:
        raise SystemExit(
            f"Refusing canonical manifest sync: master target {master_target or 'missing'} != {target}"
        )
    today_games = master.get("today_games") if isinstance(master.get("today_games"), list) else []
    games = sorted({str(g.get("game") or "").strip() for g in today_games if isinstance(g, dict) and g.get("game")})
    if not games:
        games = sorted({str(r.get("game") or "").strip() for r in props_output.get("rows", []) if r.get("game")})
    teams = sorted({
        str(g.get(k) or "").strip()
        for g in today_games if isinstance(g, dict)
        for k in ("away_team", "home_team")
        if str(g.get(k) or "").strip()
    })
    if not teams:
        teams = sorted({
            str(r.get(k) or "").strip()
            for r in props_output.get("rows", [])
            for k in ("away_team", "home_team")
            if str(r.get(k) or "").strip()
        })
    manifest = {
        "schema_version": "daily-canonical-v1",
        "generated_at_utc": props_output.get("generated_at_utc"),
        "target_date": target,
        "status": "PASS",
        "games": games,
        "teams": teams,
        "game_count": len(games),
        "player_prop_rows": int(props_output.get("row_count") or 0),
        "player_props_source": props_output.get("source"),
        "player_props_api_called": props_output.get("api_called"),
        "sportsbooks_allowed": props_output.get("sportsbooks_allowed") or sorted(PRODUCTION_BOOKS),
        "sportsbooks_observed": props_output.get("sportsbooks_observed") or [],
        "unsupported_bookmakers_rejected": props_output.get("unsupported_bookmakers_rejected") or [],
        "sources": {
            "slate": "data/dashboard/wnba_master.json",
            "player_props": "data/dashboard/wnba_player_props.json",
        },
        "steps": [
            {
                "script": "wnba_current_slate.py",
                "status": "ok",
                "returncode": 0,
                "stdout": f"Authoritative current slate synchronized for {target}",
                "stderr": "",
            },
            {
                "script": "wnba_player_props_ingestion.py",
                "status": "ok",
                "returncode": 0,
                "stdout": f"Verified player props synchronized for {target}",
                "stderr": "",
            },
        ],
        "failures": [],
        "manifest_sync_source": "player_props_ingestion_same_run",
    }
    (DASH / "wnba_daily_canonical_manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", required=True)
    ap.add_argument(
        "--from-raw-cache",
        action="store_true",
        help="Rebuild from the exact-date persisted Odds API response without a live request",
    )
    args = ap.parse_args()
    target = args.date
    api_key = os.getenv("ODDS_API_KEY", "").strip()
    if not api_key and not args.from_raw_cache:
        raise SystemExit("ODDS_API_KEY is required")

    DASH.mkdir(parents=True, exist_ok=True)
    RAW.mkdir(parents=True, exist_ok=True)
    raw_path = RAW / f"wnba_player_props_{target}.json"
    if args.from_raw_cache:
        cached = load_json(raw_path, [])
        if not isinstance(cached, list) or not cached:
            raise SystemExit(f"Exact-date raw player-prop cache is missing or empty: {raw_path}")
        cached_dates = {event_date(e.get("commence_time")) for e in cached if isinstance(e, dict)}
        if cached_dates != {target}:
            raise SystemExit(
                f"Raw player-prop cache date mismatch: expected {target}, found {sorted(cached_dates)}"
            )
        events = [e for e in cached if isinstance(e, dict)]
        api_called = False
    else:
        import requests

        session = requests.Session()
        events_resp = session.get(f"{BASE}/sports/{SPORT}/events", params={"apiKey": api_key}, timeout=30)
        events_resp.raise_for_status()
        events = [e for e in events_resp.json() if event_date(e.get("commence_time")) == target]
        api_called = True
    teams_by_player = roster_map()
    grouped: dict[tuple, dict] = {}
    raw_events = []
    observed_books: set[str] = set()
    rejected_books: set[str] = set()

    for event in events:
        event_id = event["id"]
        away = str(event.get("away_team") or "").strip()
        home = str(event.get("home_team") or "").strip()
        game = f"{away} @ {home}"
        if args.from_raw_cache:
            payload = event
        else:
            resp = session.get(
                f"{BASE}/sports/{SPORT}/events/{event_id}/odds",
                params={
                    "apiKey": api_key,
                    "bookmakers": PRODUCTION_BOOKMAKERS,
                    "markets": ",".join(MARKETS),
                    "oddsFormat": "american",
                    "dateFormat": "iso",
                },
                timeout=45,
            )
            if resp.status_code == 404:
                continue
            resp.raise_for_status()
            payload = resp.json()
        payload, payload_books, payload_rejected = filter_supported_bookmakers(payload)
        observed_books.update(payload_books)
        rejected_books.update(payload_rejected)
        raw_events.append(payload)
        for book in payload.get("bookmakers", []):
            book_key = normalize_book_key(book)
            if not book_key:
                continue
            book_name = PRODUCTION_BOOKS[book_key]
            for market in book.get("markets", []):
                stat = STAT_MAP.get(market.get("key"))
                if not stat:
                    continue
                for outcome in market.get("outcomes", []):
                    player = str(outcome.get("description") or "").strip()
                    side = str(outcome.get("name") or "").upper().strip()
                    line = outcome.get("point")
                    price = outcome.get("price")
                    if not player or side not in {"OVER", "UNDER"} or line is None:
                        continue
                    team, team_source = resolve_team(player, away, home, teams_by_player)
                    key = (event_id, player_key(player), stat, float(line))
                    row = grouped.setdefault(key, {
                        "target_date": target,
                        "event_id": event_id,
                        "commence_time": event.get("commence_time"),
                        "game": game,
                        "away_team": away,
                        "home_team": home,
                        "player": player,
                        "team": team,
                        "team_source": team_source,
                        "stat": stat,
                        "line": float(line),
                        "books": [],
                    })
                    if not row.get("team") and team:
                        row["team"] = team
                        row["team_source"] = team_source
                    row["books"].append({"book": book_name, "side": side, "price": price})

    if events and not grouped:
        raise SystemExit(
            "No supported DraftKings, FanDuel, or Fanatics standard player props were available"
        )

    verified_rows = []
    unresolved_rows = []
    for row in grouped.values():
        overs = [x for x in row["books"] if x["side"] == "OVER" and isinstance(x.get("price"), (int, float))]
        unders = [x for x in row["books"] if x["side"] == "UNDER" and isinstance(x.get("price"), (int, float))]
        best_over = max(overs, key=lambda x: x["price"], default={})
        best_under = max(unders, key=lambda x: x["price"], default={})
        row.update({
            "best_over_book": best_over.get("book"),
            "best_over_price": best_over.get("price"),
            "best_under_book": best_under.get("book"),
            "best_under_price": best_under.get("price"),
            "book_count": len({x["book"] for x in row["books"]}),
        })
        if row.get("team") in {row.get("away_team"), row.get("home_team")}:
            verified_rows.append(row)
        else:
            unresolved_rows.append(row)

    sort_key = lambda r: (r["game"], r["player"], r["stat"], r["line"])
    output = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "target_date": target,
        "source": "the_odds_api_raw_cache" if args.from_raw_cache else "the_odds_api_event_markets",
        "api_called": api_called,
        "sportsbooks_allowed": sorted(PRODUCTION_BOOKS),
        "sportsbooks_observed": sorted(observed_books),
        "unsupported_bookmakers_rejected": sorted(rejected_books),
        "event_count": len(events),
        "raw_row_count": len(grouped),
        "row_count": len(verified_rows),
        "unresolved_row_count": len(unresolved_rows),
        "rows": sorted(verified_rows, key=sort_key),
        "unresolved_rows": sorted(unresolved_rows, key=sort_key),
    }
    (DASH / "wnba_player_props.json").write_text(json.dumps(output, indent=2), encoding="utf-8")
    raw_path.write_text(json.dumps(raw_events, indent=2), encoding="utf-8")
    sync_canonical_manifest(target, output)
    print(json.dumps({
        "target_date": target,
        "events": len(events),
        "raw_rows": len(grouped),
        "verified_rows": len(verified_rows),
        "unresolved_rows": len(unresolved_rows),
        "unresolved_players": sorted({r["player"] for r in unresolved_rows}),
        "api_called": api_called,
        "sportsbooks_allowed": sorted(PRODUCTION_BOOKS),
        "sportsbooks_observed": sorted(observed_books),
        "unsupported_bookmakers_rejected": sorted(rejected_books),
        "canonical_manifest_synced": True,
    }, indent=2))


if __name__ == "__main__":
    main()
